server: 
  port: 8085
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/machinelearning
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQLDialect