server: 
  port: 8085
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3301/machinelearning
    username: root
    password: 08112001
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect